function verifica() {
if(document.form.table01.value==document.form.table02.value) { alert("Obrigatório que informe todos os campos corretamente."); return false; }
if(document.form.table01.value==document.form.table03.value) { alert("Posição 01 não pode ser igual a Posição 03 "); return false; }
if(document.form.table01.value==document.form.table04.value) { alert("Posição 01 não pode ser igual a Posição 04 "); return false; }
if(document.form.table01.value==document.form.table05.value) { alert("Posição 01 não pode ser igual a Posição 05 "); return false; }
if(document.form.table01.value==document.form.table06.value) { alert("Posição 01 não pode ser igual a Posição 06 "); return false; }
if(document.form.table01.value==document.form.table07.value) { alert("Posição 01 não pode ser igual a Posição 07 "); return false; }
if(document.form.table01.value==document.form.table08.value) { alert("Posição 01 não pode ser igual a Posição 08 "); return false; }
if(document.form.table01.value==document.form.table09.value) { alert("Posição 01 não pode ser igual a Posição 09 "); return false; }
if(document.form.table01.value==document.form.table10.value) { alert("Posição 01 não pode ser igual a Posição 10 "); return false; }
if(document.form.table01.value==document.form.table11.value) { alert("Posição 01 não pode ser igual a Posição 11 "); return false; }
if(document.form.table01.value==document.form.table12.value) { alert("Posição 01 não pode ser igual a Posição 12 "); return false; }
if(document.form.table01.value==document.form.table13.value) { alert("Posição 01 não pode ser igual a Posição 13 "); return false; }
if(document.form.table01.value==document.form.table14.value) { alert("Posição 01 não pode ser igual a Posição 14 "); return false; }
if(document.form.table01.value==document.form.table15.value) { alert("Posição 01 não pode ser igual a Posição 15 "); return false; }
if(document.form.table01.value==document.form.table16.value) { alert("Posição 01 não pode ser igual a Posição 16 "); return false; }
if(document.form.table01.value==document.form.table17.value) { alert("Posição 01 não pode ser igual a Posição 17 "); return false; }
if(document.form.table01.value==document.form.table18.value) { alert("Posição 01 não pode ser igual a Posição 18 "); return false; }
if(document.form.table01.value==document.form.table19.value) { alert("Posição 01 não pode ser igual a Posição 19 "); return false; }
if(document.form.table01.value==document.form.table20.value) { alert("Posição 01 não pode ser igual a Posição 20 "); return false; }
if(document.form.table01.value==document.form.table21.value) { alert("Posição 01 não pode ser igual a Posição 21 "); return false; }
if(document.form.table01.value==document.form.table22.value) { alert("Posição 01 não pode ser igual a Posição 22 "); return false; }
if(document.form.table01.value==document.form.table23.value) { alert("Posição 01 não pode ser igual a Posição 23 "); return false; }
if(document.form.table01.value==document.form.table24.value) { alert("Posição 01 não pode ser igual a Posição 24 "); return false; }
if(document.form.table01.value==document.form.table25.value) { alert("Posição 01 não pode ser igual a Posição 25 "); return false; }
if(document.form.table01.value==document.form.table26.value) { alert("Posição 01 não pode ser igual a Posição 26 "); return false; }
if(document.form.table01.value==document.form.table27.value) { alert("Posição 01 não pode ser igual a Posição 27 "); return false; }
if(document.form.table01.value==document.form.table28.value) { alert("Posição 01 não pode ser igual a Posição 28 "); return false; }
if(document.form.table01.value==document.form.table29.value) { alert("Posição 01 não pode ser igual a Posição 29 "); return false; }
if(document.form.table01.value==document.form.table30.value) { alert("Posição 01 não pode ser igual a Posição 30 "); return false; }
if(document.form.table01.value==document.form.table31.value) { alert("Posição 01 não pode ser igual a Posição 31 "); return false; }
if(document.form.table01.value==document.form.table32.value) { alert("Posição 01 não pode ser igual a Posição 32 "); return false; }
if(document.form.table01.value==document.form.table33.value) { alert("Posição 01 não pode ser igual a Posição 33 "); return false; }
if(document.form.table01.value==document.form.table34.value) { alert("Posição 01 não pode ser igual a Posição 34 "); return false; }
if(document.form.table01.value==document.form.table35.value) { alert("Posição 01 não pode ser igual a Posição 35 "); return false; }
if(document.form.table01.value==document.form.table36.value) { alert("Posição 01 não pode ser igual a Posição 36 "); return false; }
if(document.form.table01.value==document.form.table37.value) { alert("Posição 01 não pode ser igual a Posição 37 "); return false; }
if(document.form.table01.value==document.form.table38.value) { alert("Posição 01 não pode ser igual a Posição 38 "); return false; }
if(document.form.table01.value==document.form.table39.value) { alert("Posição 01 não pode ser igual a Posição 39 "); return false; }
if(document.form.table01.value==document.form.table40.value) { alert("Posição 01 não pode ser igual a Posição 40 "); return false; }
if(document.form.table01.value==document.form.table41.value) { alert("Posição 01 não pode ser igual a Posição 41 "); return false; }
if(document.form.table01.value==document.form.table42.value) { alert("Posição 01 não pode ser igual a Posição 42 "); return false; }
if(document.form.table01.value==document.form.table43.value) { alert("Posição 01 não pode ser igual a Posição 43 "); return false; }
if(document.form.table01.value==document.form.table44.value) { alert("Posição 01 não pode ser igual a Posição 44 "); return false; }
if(document.form.table01.value==document.form.table45.value) { alert("Posição 01 não pode ser igual a Posição 45 "); return false; }
if(document.form.table01.value==document.form.table46.value) { alert("Posição 01 não pode ser igual a Posição 46 "); return false; }
if(document.form.table01.value==document.form.table47.value) { alert("Posição 01 não pode ser igual a Posição 47 "); return false; }
if(document.form.table01.value==document.form.table48.value) { alert("Posição 01 não pode ser igual a Posição 48 "); return false; }
if(document.form.table01.value==document.form.table49.value) { alert("Posição 01 não pode ser igual a Posição 49 "); return false; }
if(document.form.table01.value==document.form.table50.value) { alert("Posição 01 não pode ser igual a Posição 50 "); return false; }
if(document.form.table01.value==document.form.table51.value) { alert("Posição 01 não pode ser igual a Posição 51 "); return false; }
if(document.form.table01.value==document.form.table52.value) { alert("Posição 01 não pode ser igual a Posição 52 "); return false; }
if(document.form.table01.value==document.form.table53.value) { alert("Posição 01 não pode ser igual a Posição 53 "); return false; }
if(document.form.table01.value==document.form.table54.value) { alert("Posição 01 não pode ser igual a Posição 54 "); return false; }
if(document.form.table01.value==document.form.table55.value) { alert("Posição 01 não pode ser igual a Posição 55 "); return false; }
if(document.form.table01.value==document.form.table56.value) { alert("Posição 01 não pode ser igual a Posição 56 "); return false; }
if(document.form.table01.value==document.form.table57.value) { alert("Posição 01 não pode ser igual a Posição 57 "); return false; }
if(document.form.table01.value==document.form.table58.value) { alert("Posição 01 não pode ser igual a Posição 58 "); return false; }
if(document.form.table01.value==document.form.table59.value) { alert("Posição 01 não pode ser igual a Posição 59 "); return false; }
if(document.form.table01.value==document.form.table60.value) { alert("Posição 01 não pode ser igual a Posição 60 "); return false; }
if(document.form.table01.value==document.form.table61.value) { alert("Posição 01 não pode ser igual a Posição 61 "); return false; }
if(document.form.table01.value==document.form.table62.value) { alert("Posição 01 não pode ser igual a Posição 62 "); return false; }
if(document.form.table01.value==document.form.table63.value) { alert("Posição 01 não pode ser igual a Posição 63 "); return false; }
if(document.form.table01.value==document.form.table64.value) { alert("Posição 01 não pode ser igual a Posição 64 "); return false; }
if(document.form.table01.value==document.form.table65.value) { alert("Posição 01 não pode ser igual a Posição 65 "); return false; }
if(document.form.table01.value==document.form.table66.value) { alert("Posição 01 não pode ser igual a Posição 66 "); return false; }
if(document.form.table01.value==document.form.table67.value) { alert("Posição 01 não pode ser igual a Posição 67 "); return false; }
if(document.form.table01.value==document.form.table68.value) { alert("Posição 01 não pode ser igual a Posição 68 "); return false; }
if(document.form.table01.value==document.form.table69.value) { alert("Posição 01 não pode ser igual a Posição 69 "); return false; }
if(document.form.table01.value==document.form.table70.value) { alert("Posição 01 não pode ser igual a Posição 70 "); return false; }
if(document.form.table02.value==document.form.table03.value) { alert("Posição 02 não pode ser igual a Posição 03 "); return false; }
if(document.form.table02.value==document.form.table04.value) { alert("Posição 02 não pode ser igual a Posição 04 "); return false; }
if(document.form.table02.value==document.form.table05.value) { alert("Posição 02 não pode ser igual a Posição 05 "); return false; }
if(document.form.table02.value==document.form.table06.value) { alert("Posição 02 não pode ser igual a Posição 06 "); return false; }
if(document.form.table02.value==document.form.table07.value) { alert("Posição 02 não pode ser igual a Posição 07 "); return false; }
if(document.form.table02.value==document.form.table08.value) { alert("Posição 02 não pode ser igual a Posição 08 "); return false; }
if(document.form.table02.value==document.form.table09.value) { alert("Posição 02 não pode ser igual a Posição 09 "); return false; }
if(document.form.table02.value==document.form.table10.value) { alert("Posição 02 não pode ser igual a Posição 10 "); return false; }
if(document.form.table02.value==document.form.table11.value) { alert("Posição 02 não pode ser igual a Posição 11 "); return false; }
if(document.form.table02.value==document.form.table12.value) { alert("Posição 02 não pode ser igual a Posição 12 "); return false; }
if(document.form.table02.value==document.form.table13.value) { alert("Posição 02 não pode ser igual a Posição 13 "); return false; }
if(document.form.table02.value==document.form.table14.value) { alert("Posição 02 não pode ser igual a Posição 14 "); return false; }
if(document.form.table02.value==document.form.table15.value) { alert("Posição 02 não pode ser igual a Posição 15 "); return false; }
if(document.form.table02.value==document.form.table16.value) { alert("Posição 02 não pode ser igual a Posição 16 "); return false; }
if(document.form.table02.value==document.form.table17.value) { alert("Posição 02 não pode ser igual a Posição 17 "); return false; }
if(document.form.table02.value==document.form.table18.value) { alert("Posição 02 não pode ser igual a Posição 18 "); return false; }
if(document.form.table02.value==document.form.table19.value) { alert("Posição 02 não pode ser igual a Posição 19 "); return false; }
if(document.form.table02.value==document.form.table20.value) { alert("Posição 02 não pode ser igual a Posição 20 "); return false; }
if(document.form.table02.value==document.form.table21.value) { alert("Posição 02 não pode ser igual a Posição 21 "); return false; }
if(document.form.table02.value==document.form.table22.value) { alert("Posição 02 não pode ser igual a Posição 22 "); return false; }
if(document.form.table02.value==document.form.table23.value) { alert("Posição 02 não pode ser igual a Posição 23 "); return false; }
if(document.form.table02.value==document.form.table24.value) { alert("Posição 02 não pode ser igual a Posição 24 "); return false; }
if(document.form.table02.value==document.form.table25.value) { alert("Posição 02 não pode ser igual a Posição 25 "); return false; }
if(document.form.table02.value==document.form.table26.value) { alert("Posição 02 não pode ser igual a Posição 26 "); return false; }
if(document.form.table02.value==document.form.table27.value) { alert("Posição 02 não pode ser igual a Posição 27 "); return false; }
if(document.form.table02.value==document.form.table28.value) { alert("Posição 02 não pode ser igual a Posição 28 "); return false; }
if(document.form.table02.value==document.form.table29.value) { alert("Posição 02 não pode ser igual a Posição 29 "); return false; }
if(document.form.table02.value==document.form.table30.value) { alert("Posição 02 não pode ser igual a Posição 30 "); return false; }
if(document.form.table02.value==document.form.table31.value) { alert("Posição 02 não pode ser igual a Posição 31 "); return false; }
if(document.form.table02.value==document.form.table32.value) { alert("Posição 02 não pode ser igual a Posição 32 "); return false; }
if(document.form.table02.value==document.form.table33.value) { alert("Posição 02 não pode ser igual a Posição 33 "); return false; }
if(document.form.table02.value==document.form.table34.value) { alert("Posição 02 não pode ser igual a Posição 34 "); return false; }
if(document.form.table02.value==document.form.table35.value) { alert("Posição 02 não pode ser igual a Posição 35 "); return false; }
if(document.form.table02.value==document.form.table36.value) { alert("Posição 02 não pode ser igual a Posição 36 "); return false; }
if(document.form.table02.value==document.form.table37.value) { alert("Posição 02 não pode ser igual a Posição 37 "); return false; }
if(document.form.table02.value==document.form.table38.value) { alert("Posição 02 não pode ser igual a Posição 38 "); return false; }
if(document.form.table02.value==document.form.table39.value) { alert("Posição 02 não pode ser igual a Posição 39 "); return false; }
if(document.form.table02.value==document.form.table40.value) { alert("Posição 02 não pode ser igual a Posição 40 "); return false; }
if(document.form.table02.value==document.form.table41.value) { alert("Posição 02 não pode ser igual a Posição 41 "); return false; }
if(document.form.table02.value==document.form.table42.value) { alert("Posição 02 não pode ser igual a Posição 42 "); return false; }
if(document.form.table02.value==document.form.table43.value) { alert("Posição 02 não pode ser igual a Posição 43 "); return false; }
if(document.form.table02.value==document.form.table44.value) { alert("Posição 02 não pode ser igual a Posição 44 "); return false; }
if(document.form.table02.value==document.form.table45.value) { alert("Posição 02 não pode ser igual a Posição 45 "); return false; }
if(document.form.table02.value==document.form.table46.value) { alert("Posição 02 não pode ser igual a Posição 46 "); return false; }
if(document.form.table02.value==document.form.table47.value) { alert("Posição 02 não pode ser igual a Posição 47 "); return false; }
if(document.form.table02.value==document.form.table48.value) { alert("Posição 02 não pode ser igual a Posição 48 "); return false; }
if(document.form.table02.value==document.form.table49.value) { alert("Posição 02 não pode ser igual a Posição 49 "); return false; }
if(document.form.table02.value==document.form.table50.value) { alert("Posição 02 não pode ser igual a Posição 50 "); return false; }
if(document.form.table02.value==document.form.table51.value) { alert("Posição 02 não pode ser igual a Posição 51 "); return false; }
if(document.form.table02.value==document.form.table52.value) { alert("Posição 02 não pode ser igual a Posição 52 "); return false; }
if(document.form.table02.value==document.form.table53.value) { alert("Posição 02 não pode ser igual a Posição 53 "); return false; }
if(document.form.table02.value==document.form.table54.value) { alert("Posição 02 não pode ser igual a Posição 54 "); return false; }
if(document.form.table02.value==document.form.table55.value) { alert("Posição 02 não pode ser igual a Posição 55 "); return false; }
if(document.form.table02.value==document.form.table56.value) { alert("Posição 02 não pode ser igual a Posição 56 "); return false; }
if(document.form.table02.value==document.form.table57.value) { alert("Posição 02 não pode ser igual a Posição 57 "); return false; }
if(document.form.table02.value==document.form.table58.value) { alert("Posição 02 não pode ser igual a Posição 58 "); return false; }
if(document.form.table02.value==document.form.table59.value) { alert("Posição 02 não pode ser igual a Posição 59 "); return false; }
if(document.form.table02.value==document.form.table60.value) { alert("Posição 02 não pode ser igual a Posição 60 "); return false; }
if(document.form.table02.value==document.form.table61.value) { alert("Posição 02 não pode ser igual a Posição 61 "); return false; }
if(document.form.table02.value==document.form.table62.value) { alert("Posição 02 não pode ser igual a Posição 62 "); return false; }
if(document.form.table02.value==document.form.table63.value) { alert("Posição 02 não pode ser igual a Posição 63 "); return false; }
if(document.form.table02.value==document.form.table64.value) { alert("Posição 02 não pode ser igual a Posição 64 "); return false; }
if(document.form.table02.value==document.form.table65.value) { alert("Posição 02 não pode ser igual a Posição 65 "); return false; }
if(document.form.table02.value==document.form.table66.value) { alert("Posição 02 não pode ser igual a Posição 66 "); return false; }
if(document.form.table02.value==document.form.table67.value) { alert("Posição 02 não pode ser igual a Posição 67 "); return false; }
if(document.form.table02.value==document.form.table68.value) { alert("Posição 02 não pode ser igual a Posição 68 "); return false; }
if(document.form.table02.value==document.form.table69.value) { alert("Posição 02 não pode ser igual a Posição 69 "); return false; }
if(document.form.table02.value==document.form.table70.value) { alert("Posição 02 não pode ser igual a Posição 70 "); return false; }
if(document.form.table03.value==document.form.table04.value) { alert("Posição 03 não pode ser igual a Posição 04 "); return false; }
if(document.form.table03.value==document.form.table05.value) { alert("Posição 03 não pode ser igual a Posição 05 "); return false; }
if(document.form.table03.value==document.form.table06.value) { alert("Posição 03 não pode ser igual a Posição 06 "); return false; }
if(document.form.table03.value==document.form.table07.value) { alert("Posição 03 não pode ser igual a Posição 07 "); return false; }
if(document.form.table03.value==document.form.table08.value) { alert("Posição 03 não pode ser igual a Posição 08 "); return false; }
if(document.form.table03.value==document.form.table09.value) { alert("Posição 03 não pode ser igual a Posição 09 "); return false; }
if(document.form.table03.value==document.form.table10.value) { alert("Posição 03 não pode ser igual a Posição 10 "); return false; }
if(document.form.table03.value==document.form.table11.value) { alert("Posição 03 não pode ser igual a Posição 11 "); return false; }
if(document.form.table03.value==document.form.table12.value) { alert("Posição 03 não pode ser igual a Posição 12 "); return false; }
if(document.form.table03.value==document.form.table13.value) { alert("Posição 03 não pode ser igual a Posição 13 "); return false; }
if(document.form.table03.value==document.form.table14.value) { alert("Posição 03 não pode ser igual a Posição 14 "); return false; }
if(document.form.table03.value==document.form.table15.value) { alert("Posição 03 não pode ser igual a Posição 15 "); return false; }
if(document.form.table03.value==document.form.table16.value) { alert("Posição 03 não pode ser igual a Posição 16 "); return false; }
if(document.form.table03.value==document.form.table17.value) { alert("Posição 03 não pode ser igual a Posição 17 "); return false; }
if(document.form.table03.value==document.form.table18.value) { alert("Posição 03 não pode ser igual a Posição 18 "); return false; }
if(document.form.table03.value==document.form.table19.value) { alert("Posição 03 não pode ser igual a Posição 19 "); return false; }
if(document.form.table03.value==document.form.table20.value) { alert("Posição 03 não pode ser igual a Posição 20 "); return false; }
if(document.form.table03.value==document.form.table21.value) { alert("Posição 03 não pode ser igual a Posição 21 "); return false; }
if(document.form.table03.value==document.form.table22.value) { alert("Posição 03 não pode ser igual a Posição 22 "); return false; }
if(document.form.table03.value==document.form.table23.value) { alert("Posição 03 não pode ser igual a Posição 23 "); return false; }
if(document.form.table03.value==document.form.table24.value) { alert("Posição 03 não pode ser igual a Posição 24 "); return false; }
if(document.form.table03.value==document.form.table25.value) { alert("Posição 03 não pode ser igual a Posição 25 "); return false; }
if(document.form.table03.value==document.form.table26.value) { alert("Posição 03 não pode ser igual a Posição 26 "); return false; }
if(document.form.table03.value==document.form.table27.value) { alert("Posição 03 não pode ser igual a Posição 27 "); return false; }
if(document.form.table03.value==document.form.table28.value) { alert("Posição 03 não pode ser igual a Posição 28 "); return false; }
if(document.form.table03.value==document.form.table29.value) { alert("Posição 03 não pode ser igual a Posição 29 "); return false; }
if(document.form.table03.value==document.form.table30.value) { alert("Posição 03 não pode ser igual a Posição 30 "); return false; }
if(document.form.table03.value==document.form.table31.value) { alert("Posição 03 não pode ser igual a Posição 31 "); return false; }
if(document.form.table03.value==document.form.table32.value) { alert("Posição 03 não pode ser igual a Posição 32 "); return false; }
if(document.form.table03.value==document.form.table33.value) { alert("Posição 03 não pode ser igual a Posição 33 "); return false; }
if(document.form.table03.value==document.form.table34.value) { alert("Posição 03 não pode ser igual a Posição 34 "); return false; }
if(document.form.table03.value==document.form.table35.value) { alert("Posição 03 não pode ser igual a Posição 35 "); return false; }
if(document.form.table03.value==document.form.table36.value) { alert("Posição 03 não pode ser igual a Posição 36 "); return false; }
if(document.form.table03.value==document.form.table37.value) { alert("Posição 03 não pode ser igual a Posição 37 "); return false; }
if(document.form.table03.value==document.form.table38.value) { alert("Posição 03 não pode ser igual a Posição 38 "); return false; }
if(document.form.table03.value==document.form.table39.value) { alert("Posição 03 não pode ser igual a Posição 39 "); return false; }
if(document.form.table03.value==document.form.table40.value) { alert("Posição 03 não pode ser igual a Posição 40 "); return false; }
if(document.form.table03.value==document.form.table41.value) { alert("Posição 03 não pode ser igual a Posição 41 "); return false; }
if(document.form.table03.value==document.form.table42.value) { alert("Posição 03 não pode ser igual a Posição 42 "); return false; }
if(document.form.table03.value==document.form.table43.value) { alert("Posição 03 não pode ser igual a Posição 43 "); return false; }
if(document.form.table03.value==document.form.table44.value) { alert("Posição 03 não pode ser igual a Posição 44 "); return false; }
if(document.form.table03.value==document.form.table45.value) { alert("Posição 03 não pode ser igual a Posição 45 "); return false; }
if(document.form.table03.value==document.form.table46.value) { alert("Posição 03 não pode ser igual a Posição 46 "); return false; }
if(document.form.table03.value==document.form.table47.value) { alert("Posição 03 não pode ser igual a Posição 47 "); return false; }
if(document.form.table03.value==document.form.table48.value) { alert("Posição 03 não pode ser igual a Posição 48 "); return false; }
if(document.form.table03.value==document.form.table49.value) { alert("Posição 03 não pode ser igual a Posição 49 "); return false; }
if(document.form.table03.value==document.form.table50.value) { alert("Posição 03 não pode ser igual a Posição 50 "); return false; }
if(document.form.table03.value==document.form.table51.value) { alert("Posição 03 não pode ser igual a Posição 51 "); return false; }
if(document.form.table03.value==document.form.table52.value) { alert("Posição 03 não pode ser igual a Posição 52 "); return false; }
if(document.form.table03.value==document.form.table53.value) { alert("Posição 03 não pode ser igual a Posição 53 "); return false; }
if(document.form.table03.value==document.form.table54.value) { alert("Posição 03 não pode ser igual a Posição 54 "); return false; }
if(document.form.table03.value==document.form.table55.value) { alert("Posição 03 não pode ser igual a Posição 55 "); return false; }
if(document.form.table03.value==document.form.table56.value) { alert("Posição 03 não pode ser igual a Posição 56 "); return false; }
if(document.form.table03.value==document.form.table57.value) { alert("Posição 03 não pode ser igual a Posição 57 "); return false; }
if(document.form.table03.value==document.form.table58.value) { alert("Posição 03 não pode ser igual a Posição 58 "); return false; }
if(document.form.table03.value==document.form.table59.value) { alert("Posição 03 não pode ser igual a Posição 59 "); return false; }
if(document.form.table03.value==document.form.table60.value) { alert("Posição 03 não pode ser igual a Posição 60 "); return false; }
if(document.form.table03.value==document.form.table61.value) { alert("Posição 03 não pode ser igual a Posição 61 "); return false; }
if(document.form.table03.value==document.form.table62.value) { alert("Posição 03 não pode ser igual a Posição 62 "); return false; }
if(document.form.table03.value==document.form.table63.value) { alert("Posição 03 não pode ser igual a Posição 63 "); return false; }
if(document.form.table03.value==document.form.table64.value) { alert("Posição 03 não pode ser igual a Posição 64 "); return false; }
if(document.form.table03.value==document.form.table65.value) { alert("Posição 03 não pode ser igual a Posição 65 "); return false; }
if(document.form.table03.value==document.form.table66.value) { alert("Posição 03 não pode ser igual a Posição 66 "); return false; }
if(document.form.table03.value==document.form.table67.value) { alert("Posição 03 não pode ser igual a Posição 67 "); return false; }
if(document.form.table03.value==document.form.table68.value) { alert("Posição 03 não pode ser igual a Posição 68 "); return false; }
if(document.form.table03.value==document.form.table69.value) { alert("Posição 03 não pode ser igual a Posição 69 "); return false; }
if(document.form.table03.value==document.form.table70.value) { alert("Posição 03 não pode ser igual a Posição 70 "); return false; }
if(document.form.table04.value==document.form.table05.value) { alert("Posição 04 não pode ser igual a Posição 05 "); return false; }
if(document.form.table04.value==document.form.table06.value) { alert("Posição 04 não pode ser igual a Posição 06 "); return false; }
if(document.form.table04.value==document.form.table07.value) { alert("Posição 04 não pode ser igual a Posição 07 "); return false; }
if(document.form.table04.value==document.form.table08.value) { alert("Posição 04 não pode ser igual a Posição 08 "); return false; }
if(document.form.table04.value==document.form.table09.value) { alert("Posição 04 não pode ser igual a Posição 09 "); return false; }
if(document.form.table04.value==document.form.table10.value) { alert("Posição 04 não pode ser igual a Posição 10 "); return false; }
if(document.form.table04.value==document.form.table11.value) { alert("Posição 04 não pode ser igual a Posição 11 "); return false; }
if(document.form.table04.value==document.form.table12.value) { alert("Posição 04 não pode ser igual a Posição 12 "); return false; }
if(document.form.table04.value==document.form.table13.value) { alert("Posição 04 não pode ser igual a Posição 13 "); return false; }
if(document.form.table04.value==document.form.table14.value) { alert("Posição 04 não pode ser igual a Posição 14 "); return false; }
if(document.form.table04.value==document.form.table15.value) { alert("Posição 04 não pode ser igual a Posição 15 "); return false; }
if(document.form.table04.value==document.form.table16.value) { alert("Posição 04 não pode ser igual a Posição 16 "); return false; }
if(document.form.table04.value==document.form.table17.value) { alert("Posição 04 não pode ser igual a Posição 17 "); return false; }
if(document.form.table04.value==document.form.table18.value) { alert("Posição 04 não pode ser igual a Posição 18 "); return false; }
if(document.form.table04.value==document.form.table19.value) { alert("Posição 04 não pode ser igual a Posição 19 "); return false; }
if(document.form.table04.value==document.form.table20.value) { alert("Posição 04 não pode ser igual a Posição 20 "); return false; }
if(document.form.table04.value==document.form.table21.value) { alert("Posição 04 não pode ser igual a Posição 21 "); return false; }
if(document.form.table04.value==document.form.table22.value) { alert("Posição 04 não pode ser igual a Posição 22 "); return false; }
if(document.form.table04.value==document.form.table23.value) { alert("Posição 04 não pode ser igual a Posição 23 "); return false; }
if(document.form.table04.value==document.form.table24.value) { alert("Posição 04 não pode ser igual a Posição 24 "); return false; }
if(document.form.table04.value==document.form.table25.value) { alert("Posição 04 não pode ser igual a Posição 25 "); return false; }
if(document.form.table04.value==document.form.table26.value) { alert("Posição 04 não pode ser igual a Posição 26 "); return false; }
if(document.form.table04.value==document.form.table27.value) { alert("Posição 04 não pode ser igual a Posição 27 "); return false; }
if(document.form.table04.value==document.form.table28.value) { alert("Posição 04 não pode ser igual a Posição 28 "); return false; }
if(document.form.table04.value==document.form.table29.value) { alert("Posição 04 não pode ser igual a Posição 29 "); return false; }
if(document.form.table04.value==document.form.table30.value) { alert("Posição 04 não pode ser igual a Posição 30 "); return false; }
if(document.form.table04.value==document.form.table31.value) { alert("Posição 04 não pode ser igual a Posição 31 "); return false; }
if(document.form.table04.value==document.form.table32.value) { alert("Posição 04 não pode ser igual a Posição 32 "); return false; }
if(document.form.table04.value==document.form.table33.value) { alert("Posição 04 não pode ser igual a Posição 33 "); return false; }
if(document.form.table04.value==document.form.table34.value) { alert("Posição 04 não pode ser igual a Posição 34 "); return false; }
if(document.form.table04.value==document.form.table35.value) { alert("Posição 04 não pode ser igual a Posição 35 "); return false; }
if(document.form.table04.value==document.form.table36.value) { alert("Posição 04 não pode ser igual a Posição 36 "); return false; }
if(document.form.table04.value==document.form.table37.value) { alert("Posição 04 não pode ser igual a Posição 37 "); return false; }
if(document.form.table04.value==document.form.table38.value) { alert("Posição 04 não pode ser igual a Posição 38 "); return false; }
if(document.form.table04.value==document.form.table39.value) { alert("Posição 04 não pode ser igual a Posição 39 "); return false; }
if(document.form.table04.value==document.form.table40.value) { alert("Posição 04 não pode ser igual a Posição 40 "); return false; }
if(document.form.table04.value==document.form.table41.value) { alert("Posição 04 não pode ser igual a Posição 41 "); return false; }
if(document.form.table04.value==document.form.table42.value) { alert("Posição 04 não pode ser igual a Posição 42 "); return false; }
if(document.form.table04.value==document.form.table43.value) { alert("Posição 04 não pode ser igual a Posição 43 "); return false; }
if(document.form.table04.value==document.form.table44.value) { alert("Posição 04 não pode ser igual a Posição 44 "); return false; }
if(document.form.table04.value==document.form.table45.value) { alert("Posição 04 não pode ser igual a Posição 45 "); return false; }
if(document.form.table04.value==document.form.table46.value) { alert("Posição 04 não pode ser igual a Posição 46 "); return false; }
if(document.form.table04.value==document.form.table47.value) { alert("Posição 04 não pode ser igual a Posição 47 "); return false; }
if(document.form.table04.value==document.form.table48.value) { alert("Posição 04 não pode ser igual a Posição 48 "); return false; }
if(document.form.table04.value==document.form.table49.value) { alert("Posição 04 não pode ser igual a Posição 49 "); return false; }
if(document.form.table04.value==document.form.table50.value) { alert("Posição 04 não pode ser igual a Posição 50 "); return false; }
if(document.form.table04.value==document.form.table51.value) { alert("Posição 04 não pode ser igual a Posição 51 "); return false; }
if(document.form.table04.value==document.form.table52.value) { alert("Posição 04 não pode ser igual a Posição 52 "); return false; }
if(document.form.table04.value==document.form.table53.value) { alert("Posição 04 não pode ser igual a Posição 53 "); return false; }
if(document.form.table04.value==document.form.table54.value) { alert("Posição 04 não pode ser igual a Posição 54 "); return false; }
if(document.form.table04.value==document.form.table55.value) { alert("Posição 04 não pode ser igual a Posição 55 "); return false; }
if(document.form.table04.value==document.form.table56.value) { alert("Posição 04 não pode ser igual a Posição 56 "); return false; }
if(document.form.table04.value==document.form.table57.value) { alert("Posição 04 não pode ser igual a Posição 57 "); return false; }
if(document.form.table04.value==document.form.table58.value) { alert("Posição 04 não pode ser igual a Posição 58 "); return false; }
if(document.form.table04.value==document.form.table59.value) { alert("Posição 04 não pode ser igual a Posição 59 "); return false; }
if(document.form.table04.value==document.form.table60.value) { alert("Posição 04 não pode ser igual a Posição 60 "); return false; }
if(document.form.table04.value==document.form.table61.value) { alert("Posição 04 não pode ser igual a Posição 61 "); return false; }
if(document.form.table04.value==document.form.table62.value) { alert("Posição 04 não pode ser igual a Posição 62 "); return false; }
if(document.form.table04.value==document.form.table63.value) { alert("Posição 04 não pode ser igual a Posição 63 "); return false; }
if(document.form.table04.value==document.form.table64.value) { alert("Posição 04 não pode ser igual a Posição 64 "); return false; }
if(document.form.table04.value==document.form.table65.value) { alert("Posição 04 não pode ser igual a Posição 65 "); return false; }
if(document.form.table04.value==document.form.table66.value) { alert("Posição 04 não pode ser igual a Posição 66 "); return false; }
if(document.form.table04.value==document.form.table67.value) { alert("Posição 04 não pode ser igual a Posição 67 "); return false; }
if(document.form.table04.value==document.form.table68.value) { alert("Posição 04 não pode ser igual a Posição 68 "); return false; }
if(document.form.table04.value==document.form.table69.value) { alert("Posição 04 não pode ser igual a Posição 69 "); return false; }
if(document.form.table04.value==document.form.table70.value) { alert("Posição 04 não pode ser igual a Posição 70 "); return false; }
if(document.form.table05.value==document.form.table06.value) { alert("Posição 05 não pode ser igual a Posição 06 "); return false; }
if(document.form.table05.value==document.form.table07.value) { alert("Posição 05 não pode ser igual a Posição 07 "); return false; }
if(document.form.table05.value==document.form.table08.value) { alert("Posição 05 não pode ser igual a Posição 08 "); return false; }
if(document.form.table05.value==document.form.table09.value) { alert("Posição 05 não pode ser igual a Posição 09 "); return false; }
if(document.form.table05.value==document.form.table10.value) { alert("Posição 05 não pode ser igual a Posição 10 "); return false; }
if(document.form.table05.value==document.form.table11.value) { alert("Posição 05 não pode ser igual a Posição 11 "); return false; }
if(document.form.table05.value==document.form.table12.value) { alert("Posição 05 não pode ser igual a Posição 12 "); return false; }
if(document.form.table05.value==document.form.table13.value) { alert("Posição 05 não pode ser igual a Posição 13 "); return false; }
if(document.form.table05.value==document.form.table14.value) { alert("Posição 05 não pode ser igual a Posição 14 "); return false; }
if(document.form.table05.value==document.form.table15.value) { alert("Posição 05 não pode ser igual a Posição 15 "); return false; }
if(document.form.table05.value==document.form.table16.value) { alert("Posição 05 não pode ser igual a Posição 16 "); return false; }
if(document.form.table05.value==document.form.table17.value) { alert("Posição 05 não pode ser igual a Posição 17 "); return false; }
if(document.form.table05.value==document.form.table18.value) { alert("Posição 05 não pode ser igual a Posição 18 "); return false; }
if(document.form.table05.value==document.form.table19.value) { alert("Posição 05 não pode ser igual a Posição 19 "); return false; }
if(document.form.table05.value==document.form.table20.value) { alert("Posição 05 não pode ser igual a Posição 20 "); return false; }
if(document.form.table05.value==document.form.table21.value) { alert("Posição 05 não pode ser igual a Posição 21 "); return false; }
if(document.form.table05.value==document.form.table22.value) { alert("Posição 05 não pode ser igual a Posição 22 "); return false; }
if(document.form.table05.value==document.form.table23.value) { alert("Posição 05 não pode ser igual a Posição 23 "); return false; }
if(document.form.table05.value==document.form.table24.value) { alert("Posição 05 não pode ser igual a Posição 24 "); return false; }
if(document.form.table05.value==document.form.table25.value) { alert("Posição 05 não pode ser igual a Posição 25 "); return false; }
if(document.form.table05.value==document.form.table26.value) { alert("Posição 05 não pode ser igual a Posição 26 "); return false; }
if(document.form.table05.value==document.form.table27.value) { alert("Posição 05 não pode ser igual a Posição 27 "); return false; }
if(document.form.table05.value==document.form.table28.value) { alert("Posição 05 não pode ser igual a Posição 28 "); return false; }
if(document.form.table05.value==document.form.table29.value) { alert("Posição 05 não pode ser igual a Posição 29 "); return false; }
if(document.form.table05.value==document.form.table30.value) { alert("Posição 05 não pode ser igual a Posição 30 "); return false; }
if(document.form.table05.value==document.form.table31.value) { alert("Posição 05 não pode ser igual a Posição 31 "); return false; }
if(document.form.table05.value==document.form.table32.value) { alert("Posição 05 não pode ser igual a Posição 32 "); return false; }
if(document.form.table05.value==document.form.table33.value) { alert("Posição 05 não pode ser igual a Posição 33 "); return false; }
if(document.form.table05.value==document.form.table34.value) { alert("Posição 05 não pode ser igual a Posição 34 "); return false; }
if(document.form.table05.value==document.form.table35.value) { alert("Posição 05 não pode ser igual a Posição 35 "); return false; }
if(document.form.table05.value==document.form.table36.value) { alert("Posição 05 não pode ser igual a Posição 36 "); return false; }
if(document.form.table05.value==document.form.table37.value) { alert("Posição 05 não pode ser igual a Posição 37 "); return false; }
if(document.form.table05.value==document.form.table38.value) { alert("Posição 05 não pode ser igual a Posição 38 "); return false; }
if(document.form.table05.value==document.form.table39.value) { alert("Posição 05 não pode ser igual a Posição 39 "); return false; }
if(document.form.table05.value==document.form.table40.value) { alert("Posição 05 não pode ser igual a Posição 40 "); return false; }
if(document.form.table05.value==document.form.table41.value) { alert("Posição 05 não pode ser igual a Posição 41 "); return false; }
if(document.form.table05.value==document.form.table42.value) { alert("Posição 05 não pode ser igual a Posição 42 "); return false; }
if(document.form.table05.value==document.form.table43.value) { alert("Posição 05 não pode ser igual a Posição 43 "); return false; }
if(document.form.table05.value==document.form.table44.value) { alert("Posição 05 não pode ser igual a Posição 44 "); return false; }
if(document.form.table05.value==document.form.table45.value) { alert("Posição 05 não pode ser igual a Posição 45 "); return false; }
if(document.form.table05.value==document.form.table46.value) { alert("Posição 05 não pode ser igual a Posição 46 "); return false; }
if(document.form.table05.value==document.form.table47.value) { alert("Posição 05 não pode ser igual a Posição 47 "); return false; }
if(document.form.table05.value==document.form.table48.value) { alert("Posição 05 não pode ser igual a Posição 48 "); return false; }
if(document.form.table05.value==document.form.table49.value) { alert("Posição 05 não pode ser igual a Posição 49 "); return false; }
if(document.form.table05.value==document.form.table50.value) { alert("Posição 05 não pode ser igual a Posição 50 "); return false; }
if(document.form.table05.value==document.form.table51.value) { alert("Posição 05 não pode ser igual a Posição 51 "); return false; }
if(document.form.table05.value==document.form.table52.value) { alert("Posição 05 não pode ser igual a Posição 52 "); return false; }
if(document.form.table05.value==document.form.table53.value) { alert("Posição 05 não pode ser igual a Posição 53 "); return false; }
if(document.form.table05.value==document.form.table54.value) { alert("Posição 05 não pode ser igual a Posição 54 "); return false; }
if(document.form.table05.value==document.form.table55.value) { alert("Posição 05 não pode ser igual a Posição 55 "); return false; }
if(document.form.table05.value==document.form.table56.value) { alert("Posição 05 não pode ser igual a Posição 56 "); return false; }
if(document.form.table05.value==document.form.table57.value) { alert("Posição 05 não pode ser igual a Posição 57 "); return false; }
if(document.form.table05.value==document.form.table58.value) { alert("Posição 05 não pode ser igual a Posição 58 "); return false; }
if(document.form.table05.value==document.form.table59.value) { alert("Posição 05 não pode ser igual a Posição 59 "); return false; }
if(document.form.table05.value==document.form.table60.value) { alert("Posição 05 não pode ser igual a Posição 60 "); return false; }
if(document.form.table05.value==document.form.table61.value) { alert("Posição 05 não pode ser igual a Posição 61 "); return false; }
if(document.form.table05.value==document.form.table62.value) { alert("Posição 05 não pode ser igual a Posição 62 "); return false; }
if(document.form.table05.value==document.form.table63.value) { alert("Posição 05 não pode ser igual a Posição 63 "); return false; }
if(document.form.table05.value==document.form.table64.value) { alert("Posição 05 não pode ser igual a Posição 64 "); return false; }
if(document.form.table05.value==document.form.table65.value) { alert("Posição 05 não pode ser igual a Posição 65 "); return false; }
if(document.form.table05.value==document.form.table66.value) { alert("Posição 05 não pode ser igual a Posição 66 "); return false; }
if(document.form.table05.value==document.form.table67.value) { alert("Posição 05 não pode ser igual a Posição 67 "); return false; }
if(document.form.table05.value==document.form.table68.value) { alert("Posição 05 não pode ser igual a Posição 68 "); return false; }
if(document.form.table05.value==document.form.table69.value) { alert("Posição 05 não pode ser igual a Posição 69 "); return false; }
if(document.form.table05.value==document.form.table70.value) { alert("Posição 05 não pode ser igual a Posição 70 "); return false; }
if(document.form.table06.value==document.form.table07.value) { alert("Posição 06 não pode ser igual a Posição 07 "); return false; }
if(document.form.table06.value==document.form.table08.value) { alert("Posição 06 não pode ser igual a Posição 08 "); return false; }
if(document.form.table06.value==document.form.table09.value) { alert("Posição 06 não pode ser igual a Posição 09 "); return false; }
if(document.form.table06.value==document.form.table10.value) { alert("Posição 06 não pode ser igual a Posição 10 "); return false; }
if(document.form.table06.value==document.form.table11.value) { alert("Posição 06 não pode ser igual a Posição 11 "); return false; }
if(document.form.table06.value==document.form.table12.value) { alert("Posição 06 não pode ser igual a Posição 12 "); return false; }
if(document.form.table06.value==document.form.table13.value) { alert("Posição 06 não pode ser igual a Posição 13 "); return false; }
if(document.form.table06.value==document.form.table14.value) { alert("Posição 06 não pode ser igual a Posição 14 "); return false; }
if(document.form.table06.value==document.form.table15.value) { alert("Posição 06 não pode ser igual a Posição 15 "); return false; }
if(document.form.table06.value==document.form.table16.value) { alert("Posição 06 não pode ser igual a Posição 16 "); return false; }
if(document.form.table06.value==document.form.table17.value) { alert("Posição 06 não pode ser igual a Posição 17 "); return false; }
if(document.form.table06.value==document.form.table18.value) { alert("Posição 06 não pode ser igual a Posição 18 "); return false; }
if(document.form.table06.value==document.form.table19.value) { alert("Posição 06 não pode ser igual a Posição 19 "); return false; }
if(document.form.table06.value==document.form.table20.value) { alert("Posição 06 não pode ser igual a Posição 20 "); return false; }
if(document.form.table06.value==document.form.table21.value) { alert("Posição 06 não pode ser igual a Posição 21 "); return false; }
if(document.form.table06.value==document.form.table22.value) { alert("Posição 06 não pode ser igual a Posição 22 "); return false; }
if(document.form.table06.value==document.form.table23.value) { alert("Posição 06 não pode ser igual a Posição 23 "); return false; }
if(document.form.table06.value==document.form.table24.value) { alert("Posição 06 não pode ser igual a Posição 24 "); return false; }
if(document.form.table06.value==document.form.table25.value) { alert("Posição 06 não pode ser igual a Posição 25 "); return false; }
if(document.form.table06.value==document.form.table26.value) { alert("Posição 06 não pode ser igual a Posição 26 "); return false; }
if(document.form.table06.value==document.form.table27.value) { alert("Posição 06 não pode ser igual a Posição 27 "); return false; }
if(document.form.table06.value==document.form.table28.value) { alert("Posição 06 não pode ser igual a Posição 28 "); return false; }
if(document.form.table06.value==document.form.table29.value) { alert("Posição 06 não pode ser igual a Posição 29 "); return false; }
if(document.form.table06.value==document.form.table30.value) { alert("Posição 06 não pode ser igual a Posição 30 "); return false; }
if(document.form.table06.value==document.form.table31.value) { alert("Posição 06 não pode ser igual a Posição 31 "); return false; }
if(document.form.table06.value==document.form.table32.value) { alert("Posição 06 não pode ser igual a Posição 32 "); return false; }
if(document.form.table06.value==document.form.table33.value) { alert("Posição 06 não pode ser igual a Posição 33 "); return false; }
if(document.form.table06.value==document.form.table34.value) { alert("Posição 06 não pode ser igual a Posição 34 "); return false; }
if(document.form.table06.value==document.form.table35.value) { alert("Posição 06 não pode ser igual a Posição 35 "); return false; }
if(document.form.table06.value==document.form.table36.value) { alert("Posição 06 não pode ser igual a Posição 36 "); return false; }
if(document.form.table06.value==document.form.table37.value) { alert("Posição 06 não pode ser igual a Posição 37 "); return false; }
if(document.form.table06.value==document.form.table38.value) { alert("Posição 06 não pode ser igual a Posição 38 "); return false; }
if(document.form.table06.value==document.form.table39.value) { alert("Posição 06 não pode ser igual a Posição 39 "); return false; }
if(document.form.table06.value==document.form.table40.value) { alert("Posição 06 não pode ser igual a Posição 40 "); return false; }
if(document.form.table06.value==document.form.table41.value) { alert("Posição 06 não pode ser igual a Posição 41 "); return false; }
if(document.form.table06.value==document.form.table42.value) { alert("Posição 06 não pode ser igual a Posição 42 "); return false; }
if(document.form.table06.value==document.form.table43.value) { alert("Posição 06 não pode ser igual a Posição 43 "); return false; }
if(document.form.table06.value==document.form.table44.value) { alert("Posição 06 não pode ser igual a Posição 44 "); return false; }
if(document.form.table06.value==document.form.table45.value) { alert("Posição 06 não pode ser igual a Posição 45 "); return false; }
if(document.form.table06.value==document.form.table46.value) { alert("Posição 06 não pode ser igual a Posição 46 "); return false; }
if(document.form.table06.value==document.form.table47.value) { alert("Posição 06 não pode ser igual a Posição 47 "); return false; }
if(document.form.table06.value==document.form.table48.value) { alert("Posição 06 não pode ser igual a Posição 48 "); return false; }
if(document.form.table06.value==document.form.table49.value) { alert("Posição 06 não pode ser igual a Posição 49 "); return false; }
if(document.form.table06.value==document.form.table50.value) { alert("Posição 06 não pode ser igual a Posição 50 "); return false; }
if(document.form.table06.value==document.form.table51.value) { alert("Posição 06 não pode ser igual a Posição 51 "); return false; }
if(document.form.table06.value==document.form.table52.value) { alert("Posição 06 não pode ser igual a Posição 52 "); return false; }
if(document.form.table06.value==document.form.table53.value) { alert("Posição 06 não pode ser igual a Posição 53 "); return false; }
if(document.form.table06.value==document.form.table54.value) { alert("Posição 06 não pode ser igual a Posição 54 "); return false; }
if(document.form.table06.value==document.form.table55.value) { alert("Posição 06 não pode ser igual a Posição 55 "); return false; }
if(document.form.table06.value==document.form.table56.value) { alert("Posição 06 não pode ser igual a Posição 56 "); return false; }
if(document.form.table06.value==document.form.table57.value) { alert("Posição 06 não pode ser igual a Posição 57 "); return false; }
if(document.form.table06.value==document.form.table58.value) { alert("Posição 06 não pode ser igual a Posição 58 "); return false; }
if(document.form.table06.value==document.form.table59.value) { alert("Posição 06 não pode ser igual a Posição 59 "); return false; }
if(document.form.table06.value==document.form.table60.value) { alert("Posição 06 não pode ser igual a Posição 60 "); return false; }
if(document.form.table06.value==document.form.table61.value) { alert("Posição 06 não pode ser igual a Posição 61 "); return false; }
if(document.form.table06.value==document.form.table62.value) { alert("Posição 06 não pode ser igual a Posição 62 "); return false; }
if(document.form.table06.value==document.form.table63.value) { alert("Posição 06 não pode ser igual a Posição 63 "); return false; }
if(document.form.table06.value==document.form.table64.value) { alert("Posição 06 não pode ser igual a Posição 64 "); return false; }
if(document.form.table06.value==document.form.table65.value) { alert("Posição 06 não pode ser igual a Posição 65 "); return false; }
if(document.form.table06.value==document.form.table66.value) { alert("Posição 06 não pode ser igual a Posição 66 "); return false; }
if(document.form.table06.value==document.form.table67.value) { alert("Posição 06 não pode ser igual a Posição 67 "); return false; }
if(document.form.table06.value==document.form.table68.value) { alert("Posição 06 não pode ser igual a Posição 68 "); return false; }
if(document.form.table06.value==document.form.table69.value) { alert("Posição 06 não pode ser igual a Posição 69 "); return false; }
if(document.form.table06.value==document.form.table70.value) { alert("Posição 06 não pode ser igual a Posição 70 "); return false; }
if(document.form.table07.value==document.form.table08.value) { alert("Posição 07 não pode ser igual a Posição 08 "); return false; }
if(document.form.table07.value==document.form.table09.value) { alert("Posição 07 não pode ser igual a Posição 09 "); return false; }
if(document.form.table07.value==document.form.table10.value) { alert("Posição 07 não pode ser igual a Posição 10 "); return false; }
if(document.form.table07.value==document.form.table11.value) { alert("Posição 07 não pode ser igual a Posição 11 "); return false; }
if(document.form.table07.value==document.form.table12.value) { alert("Posição 07 não pode ser igual a Posição 12 "); return false; }
if(document.form.table07.value==document.form.table13.value) { alert("Posição 07 não pode ser igual a Posição 13 "); return false; }
if(document.form.table07.value==document.form.table14.value) { alert("Posição 07 não pode ser igual a Posição 14 "); return false; }
if(document.form.table07.value==document.form.table15.value) { alert("Posição 07 não pode ser igual a Posição 15 "); return false; }
if(document.form.table07.value==document.form.table16.value) { alert("Posição 07 não pode ser igual a Posição 16 "); return false; }
if(document.form.table07.value==document.form.table17.value) { alert("Posição 07 não pode ser igual a Posição 17 "); return false; }
if(document.form.table07.value==document.form.table18.value) { alert("Posição 07 não pode ser igual a Posição 18 "); return false; }
if(document.form.table07.value==document.form.table19.value) { alert("Posição 07 não pode ser igual a Posição 19 "); return false; }
if(document.form.table07.value==document.form.table20.value) { alert("Posição 07 não pode ser igual a Posição 20 "); return false; }
if(document.form.table07.value==document.form.table21.value) { alert("Posição 07 não pode ser igual a Posição 21 "); return false; }
if(document.form.table07.value==document.form.table22.value) { alert("Posição 07 não pode ser igual a Posição 22 "); return false; }
if(document.form.table07.value==document.form.table23.value) { alert("Posição 07 não pode ser igual a Posição 23 "); return false; }
if(document.form.table07.value==document.form.table24.value) { alert("Posição 07 não pode ser igual a Posição 24 "); return false; }
if(document.form.table07.value==document.form.table25.value) { alert("Posição 07 não pode ser igual a Posição 25 "); return false; }
if(document.form.table07.value==document.form.table26.value) { alert("Posição 07 não pode ser igual a Posição 26 "); return false; }
if(document.form.table07.value==document.form.table27.value) { alert("Posição 07 não pode ser igual a Posição 27 "); return false; }
if(document.form.table07.value==document.form.table28.value) { alert("Posição 07 não pode ser igual a Posição 28 "); return false; }
if(document.form.table07.value==document.form.table29.value) { alert("Posição 07 não pode ser igual a Posição 29 "); return false; }
if(document.form.table07.value==document.form.table30.value) { alert("Posição 07 não pode ser igual a Posição 30 "); return false; }
if(document.form.table07.value==document.form.table31.value) { alert("Posição 07 não pode ser igual a Posição 31 "); return false; }
if(document.form.table07.value==document.form.table32.value) { alert("Posição 07 não pode ser igual a Posição 32 "); return false; }
if(document.form.table07.value==document.form.table33.value) { alert("Posição 07 não pode ser igual a Posição 33 "); return false; }
if(document.form.table07.value==document.form.table34.value) { alert("Posição 07 não pode ser igual a Posição 34 "); return false; }
if(document.form.table07.value==document.form.table35.value) { alert("Posição 07 não pode ser igual a Posição 35 "); return false; }
if(document.form.table07.value==document.form.table36.value) { alert("Posição 07 não pode ser igual a Posição 36 "); return false; }
if(document.form.table07.value==document.form.table37.value) { alert("Posição 07 não pode ser igual a Posição 37 "); return false; }
if(document.form.table07.value==document.form.table38.value) { alert("Posição 07 não pode ser igual a Posição 38 "); return false; }
if(document.form.table07.value==document.form.table39.value) { alert("Posição 07 não pode ser igual a Posição 39 "); return false; }
if(document.form.table07.value==document.form.table40.value) { alert("Posição 07 não pode ser igual a Posição 40 "); return false; }
if(document.form.table07.value==document.form.table41.value) { alert("Posição 07 não pode ser igual a Posição 41 "); return false; }
if(document.form.table07.value==document.form.table42.value) { alert("Posição 07 não pode ser igual a Posição 42 "); return false; }
if(document.form.table07.value==document.form.table43.value) { alert("Posição 07 não pode ser igual a Posição 43 "); return false; }
if(document.form.table07.value==document.form.table44.value) { alert("Posição 07 não pode ser igual a Posição 44 "); return false; }
if(document.form.table07.value==document.form.table45.value) { alert("Posição 07 não pode ser igual a Posição 45 "); return false; }
if(document.form.table07.value==document.form.table46.value) { alert("Posição 07 não pode ser igual a Posição 46 "); return false; }
if(document.form.table07.value==document.form.table47.value) { alert("Posição 07 não pode ser igual a Posição 47 "); return false; }
if(document.form.table07.value==document.form.table48.value) { alert("Posição 07 não pode ser igual a Posição 48 "); return false; }
if(document.form.table07.value==document.form.table49.value) { alert("Posição 07 não pode ser igual a Posição 49 "); return false; }
if(document.form.table07.value==document.form.table50.value) { alert("Posição 07 não pode ser igual a Posição 50 "); return false; }
if(document.form.table07.value==document.form.table51.value) { alert("Posição 07 não pode ser igual a Posição 51 "); return false; }
if(document.form.table07.value==document.form.table52.value) { alert("Posição 07 não pode ser igual a Posição 52 "); return false; }
if(document.form.table07.value==document.form.table53.value) { alert("Posição 07 não pode ser igual a Posição 53 "); return false; }
if(document.form.table07.value==document.form.table54.value) { alert("Posição 07 não pode ser igual a Posição 54 "); return false; }
if(document.form.table07.value==document.form.table55.value) { alert("Posição 07 não pode ser igual a Posição 55 "); return false; }
if(document.form.table07.value==document.form.table56.value) { alert("Posição 07 não pode ser igual a Posição 56 "); return false; }
if(document.form.table07.value==document.form.table57.value) { alert("Posição 07 não pode ser igual a Posição 57 "); return false; }
if(document.form.table07.value==document.form.table58.value) { alert("Posição 07 não pode ser igual a Posição 58 "); return false; }
if(document.form.table07.value==document.form.table59.value) { alert("Posição 07 não pode ser igual a Posição 59 "); return false; }
if(document.form.table07.value==document.form.table60.value) { alert("Posição 07 não pode ser igual a Posição 60 "); return false; }
if(document.form.table07.value==document.form.table61.value) { alert("Posição 07 não pode ser igual a Posição 61 "); return false; }
if(document.form.table07.value==document.form.table62.value) { alert("Posição 07 não pode ser igual a Posição 62 "); return false; }
if(document.form.table07.value==document.form.table63.value) { alert("Posição 07 não pode ser igual a Posição 63 "); return false; }
if(document.form.table07.value==document.form.table64.value) { alert("Posição 07 não pode ser igual a Posição 64 "); return false; }
if(document.form.table07.value==document.form.table65.value) { alert("Posição 07 não pode ser igual a Posição 65 "); return false; }
if(document.form.table07.value==document.form.table66.value) { alert("Posição 07 não pode ser igual a Posição 66 "); return false; }
if(document.form.table07.value==document.form.table67.value) { alert("Posição 07 não pode ser igual a Posição 67 "); return false; }
if(document.form.table07.value==document.form.table68.value) { alert("Posição 07 não pode ser igual a Posição 68 "); return false; }
if(document.form.table07.value==document.form.table69.value) { alert("Posição 07 não pode ser igual a Posição 69 "); return false; }
if(document.form.table07.value==document.form.table70.value) { alert("Posição 07 não pode ser igual a Posição 70 "); return false; }
if(document.form.table08.value==document.form.table09.value) { alert("Posição 08 não pode ser igual a Posição 09 "); return false; }
if(document.form.table08.value==document.form.table10.value) { alert("Posição 08 não pode ser igual a Posição 10 "); return false; }
if(document.form.table08.value==document.form.table11.value) { alert("Posição 08 não pode ser igual a Posição 11 "); return false; }
if(document.form.table08.value==document.form.table12.value) { alert("Posição 08 não pode ser igual a Posição 12 "); return false; }
if(document.form.table08.value==document.form.table13.value) { alert("Posição 08 não pode ser igual a Posição 13 "); return false; }
if(document.form.table08.value==document.form.table14.value) { alert("Posição 08 não pode ser igual a Posição 14 "); return false; }
if(document.form.table08.value==document.form.table15.value) { alert("Posição 08 não pode ser igual a Posição 15 "); return false; }
if(document.form.table08.value==document.form.table16.value) { alert("Posição 08 não pode ser igual a Posição 16 "); return false; }
if(document.form.table08.value==document.form.table17.value) { alert("Posição 08 não pode ser igual a Posição 17 "); return false; }
if(document.form.table08.value==document.form.table18.value) { alert("Posição 08 não pode ser igual a Posição 18 "); return false; }
if(document.form.table08.value==document.form.table19.value) { alert("Posição 08 não pode ser igual a Posição 19 "); return false; }
if(document.form.table08.value==document.form.table20.value) { alert("Posição 08 não pode ser igual a Posição 20 "); return false; }
if(document.form.table08.value==document.form.table21.value) { alert("Posição 08 não pode ser igual a Posição 21 "); return false; }
if(document.form.table08.value==document.form.table22.value) { alert("Posição 08 não pode ser igual a Posição 22 "); return false; }
if(document.form.table08.value==document.form.table23.value) { alert("Posição 08 não pode ser igual a Posição 23 "); return false; }
if(document.form.table08.value==document.form.table24.value) { alert("Posição 08 não pode ser igual a Posição 24 "); return false; }
if(document.form.table08.value==document.form.table25.value) { alert("Posição 08 não pode ser igual a Posição 25 "); return false; }
if(document.form.table08.value==document.form.table26.value) { alert("Posição 08 não pode ser igual a Posição 26 "); return false; }
if(document.form.table08.value==document.form.table27.value) { alert("Posição 08 não pode ser igual a Posição 27 "); return false; }
if(document.form.table08.value==document.form.table28.value) { alert("Posição 08 não pode ser igual a Posição 28 "); return false; }
if(document.form.table08.value==document.form.table29.value) { alert("Posição 08 não pode ser igual a Posição 29 "); return false; }
if(document.form.table08.value==document.form.table30.value) { alert("Posição 08 não pode ser igual a Posição 30 "); return false; }
if(document.form.table08.value==document.form.table31.value) { alert("Posição 08 não pode ser igual a Posição 31 "); return false; }
if(document.form.table08.value==document.form.table32.value) { alert("Posição 08 não pode ser igual a Posição 32 "); return false; }
if(document.form.table08.value==document.form.table33.value) { alert("Posição 08 não pode ser igual a Posição 33 "); return false; }
if(document.form.table08.value==document.form.table34.value) { alert("Posição 08 não pode ser igual a Posição 34 "); return false; }
if(document.form.table08.value==document.form.table35.value) { alert("Posição 08 não pode ser igual a Posição 35 "); return false; }
if(document.form.table08.value==document.form.table36.value) { alert("Posição 08 não pode ser igual a Posição 36 "); return false; }
if(document.form.table08.value==document.form.table37.value) { alert("Posição 08 não pode ser igual a Posição 37 "); return false; }
if(document.form.table08.value==document.form.table38.value) { alert("Posição 08 não pode ser igual a Posição 38 "); return false; }
if(document.form.table08.value==document.form.table39.value) { alert("Posição 08 não pode ser igual a Posição 39 "); return false; }
if(document.form.table08.value==document.form.table40.value) { alert("Posição 08 não pode ser igual a Posição 40 "); return false; }
if(document.form.table08.value==document.form.table41.value) { alert("Posição 08 não pode ser igual a Posição 41 "); return false; }
if(document.form.table08.value==document.form.table42.value) { alert("Posição 08 não pode ser igual a Posição 42 "); return false; }
if(document.form.table08.value==document.form.table43.value) { alert("Posição 08 não pode ser igual a Posição 43 "); return false; }
if(document.form.table08.value==document.form.table44.value) { alert("Posição 08 não pode ser igual a Posição 44 "); return false; }
if(document.form.table08.value==document.form.table45.value) { alert("Posição 08 não pode ser igual a Posição 45 "); return false; }
if(document.form.table08.value==document.form.table46.value) { alert("Posição 08 não pode ser igual a Posição 46 "); return false; }
if(document.form.table08.value==document.form.table47.value) { alert("Posição 08 não pode ser igual a Posição 47 "); return false; }
if(document.form.table08.value==document.form.table48.value) { alert("Posição 08 não pode ser igual a Posição 48 "); return false; }
if(document.form.table08.value==document.form.table49.value) { alert("Posição 08 não pode ser igual a Posição 49 "); return false; }
if(document.form.table08.value==document.form.table50.value) { alert("Posição 08 não pode ser igual a Posição 50 "); return false; }
if(document.form.table08.value==document.form.table51.value) { alert("Posição 08 não pode ser igual a Posição 51 "); return false; }
if(document.form.table08.value==document.form.table52.value) { alert("Posição 08 não pode ser igual a Posição 52 "); return false; }
if(document.form.table08.value==document.form.table53.value) { alert("Posição 08 não pode ser igual a Posição 53 "); return false; }
if(document.form.table08.value==document.form.table54.value) { alert("Posição 08 não pode ser igual a Posição 54 "); return false; }
if(document.form.table08.value==document.form.table55.value) { alert("Posição 08 não pode ser igual a Posição 55 "); return false; }
if(document.form.table08.value==document.form.table56.value) { alert("Posição 08 não pode ser igual a Posição 56 "); return false; }
if(document.form.table08.value==document.form.table57.value) { alert("Posição 08 não pode ser igual a Posição 57 "); return false; }
if(document.form.table08.value==document.form.table58.value) { alert("Posição 08 não pode ser igual a Posição 58 "); return false; }
if(document.form.table08.value==document.form.table59.value) { alert("Posição 08 não pode ser igual a Posição 59 "); return false; }
if(document.form.table08.value==document.form.table60.value) { alert("Posição 08 não pode ser igual a Posição 60 "); return false; }
if(document.form.table08.value==document.form.table61.value) { alert("Posição 08 não pode ser igual a Posição 61 "); return false; }
if(document.form.table08.value==document.form.table62.value) { alert("Posição 08 não pode ser igual a Posição 62 "); return false; }
if(document.form.table08.value==document.form.table63.value) { alert("Posição 08 não pode ser igual a Posição 63 "); return false; }
if(document.form.table08.value==document.form.table64.value) { alert("Posição 08 não pode ser igual a Posição 64 "); return false; }
if(document.form.table08.value==document.form.table65.value) { alert("Posição 08 não pode ser igual a Posição 65 "); return false; }
if(document.form.table08.value==document.form.table66.value) { alert("Posição 08 não pode ser igual a Posição 66 "); return false; }
if(document.form.table08.value==document.form.table67.value) { alert("Posição 08 não pode ser igual a Posição 67 "); return false; }
if(document.form.table08.value==document.form.table68.value) { alert("Posição 08 não pode ser igual a Posição 68 "); return false; }
if(document.form.table08.value==document.form.table69.value) { alert("Posição 08 não pode ser igual a Posição 69 "); return false; }
if(document.form.table08.value==document.form.table70.value) { alert("Posição 08 não pode ser igual a Posição 70 "); return false; }
if(document.form.table09.value==document.form.table10.value) { alert("Posição 09 não pode ser igual a Posição 10 "); return false; }
if(document.form.table09.value==document.form.table11.value) { alert("Posição 09 não pode ser igual a Posição 11 "); return false; }
if(document.form.table09.value==document.form.table12.value) { alert("Posição 09 não pode ser igual a Posição 12 "); return false; }
if(document.form.table09.value==document.form.table13.value) { alert("Posição 09 não pode ser igual a Posição 13 "); return false; }
if(document.form.table09.value==document.form.table14.value) { alert("Posição 09 não pode ser igual a Posição 14 "); return false; }
if(document.form.table09.value==document.form.table15.value) { alert("Posição 09 não pode ser igual a Posição 15 "); return false; }
if(document.form.table09.value==document.form.table16.value) { alert("Posição 09 não pode ser igual a Posição 16 "); return false; }
if(document.form.table09.value==document.form.table17.value) { alert("Posição 09 não pode ser igual a Posição 17 "); return false; }
if(document.form.table09.value==document.form.table18.value) { alert("Posição 09 não pode ser igual a Posição 18 "); return false; }
if(document.form.table09.value==document.form.table19.value) { alert("Posição 09 não pode ser igual a Posição 19 "); return false; }
if(document.form.table09.value==document.form.table20.value) { alert("Posição 09 não pode ser igual a Posição 20 "); return false; }
if(document.form.table09.value==document.form.table21.value) { alert("Posição 09 não pode ser igual a Posição 21 "); return false; }
if(document.form.table09.value==document.form.table22.value) { alert("Posição 09 não pode ser igual a Posição 22 "); return false; }
if(document.form.table09.value==document.form.table23.value) { alert("Posição 09 não pode ser igual a Posição 23 "); return false; }
if(document.form.table09.value==document.form.table24.value) { alert("Posição 09 não pode ser igual a Posição 24 "); return false; }
if(document.form.table09.value==document.form.table25.value) { alert("Posição 09 não pode ser igual a Posição 25 "); return false; }
if(document.form.table09.value==document.form.table26.value) { alert("Posição 09 não pode ser igual a Posição 26 "); return false; }
if(document.form.table09.value==document.form.table27.value) { alert("Posição 09 não pode ser igual a Posição 27 "); return false; }
if(document.form.table09.value==document.form.table28.value) { alert("Posição 09 não pode ser igual a Posição 28 "); return false; }
if(document.form.table09.value==document.form.table29.value) { alert("Posição 09 não pode ser igual a Posição 29 "); return false; }
if(document.form.table09.value==document.form.table30.value) { alert("Posição 09 não pode ser igual a Posição 30 "); return false; }
if(document.form.table09.value==document.form.table31.value) { alert("Posição 09 não pode ser igual a Posição 31 "); return false; }
if(document.form.table09.value==document.form.table32.value) { alert("Posição 09 não pode ser igual a Posição 32 "); return false; }
if(document.form.table09.value==document.form.table33.value) { alert("Posição 09 não pode ser igual a Posição 33 "); return false; }
if(document.form.table09.value==document.form.table34.value) { alert("Posição 09 não pode ser igual a Posição 34 "); return false; }
if(document.form.table09.value==document.form.table35.value) { alert("Posição 09 não pode ser igual a Posição 35 "); return false; }
if(document.form.table09.value==document.form.table36.value) { alert("Posição 09 não pode ser igual a Posição 36 "); return false; }
if(document.form.table09.value==document.form.table37.value) { alert("Posição 09 não pode ser igual a Posição 37 "); return false; }
if(document.form.table09.value==document.form.table38.value) { alert("Posição 09 não pode ser igual a Posição 38 "); return false; }
if(document.form.table09.value==document.form.table39.value) { alert("Posição 09 não pode ser igual a Posição 39 "); return false; }
if(document.form.table09.value==document.form.table40.value) { alert("Posição 09 não pode ser igual a Posição 40 "); return false; }
if(document.form.table09.value==document.form.table41.value) { alert("Posição 09 não pode ser igual a Posição 41 "); return false; }
if(document.form.table09.value==document.form.table42.value) { alert("Posição 09 não pode ser igual a Posição 42 "); return false; }
if(document.form.table09.value==document.form.table43.value) { alert("Posição 09 não pode ser igual a Posição 43 "); return false; }
if(document.form.table09.value==document.form.table44.value) { alert("Posição 09 não pode ser igual a Posição 44 "); return false; }
if(document.form.table09.value==document.form.table45.value) { alert("Posição 09 não pode ser igual a Posição 45 "); return false; }
if(document.form.table09.value==document.form.table46.value) { alert("Posição 09 não pode ser igual a Posição 46 "); return false; }
if(document.form.table09.value==document.form.table47.value) { alert("Posição 09 não pode ser igual a Posição 47 "); return false; }
if(document.form.table09.value==document.form.table48.value) { alert("Posição 09 não pode ser igual a Posição 48 "); return false; }
if(document.form.table09.value==document.form.table49.value) { alert("Posição 09 não pode ser igual a Posição 49 "); return false; }
if(document.form.table09.value==document.form.table50.value) { alert("Posição 09 não pode ser igual a Posição 50 "); return false; }
if(document.form.table09.value==document.form.table51.value) { alert("Posição 09 não pode ser igual a Posição 51 "); return false; }
if(document.form.table09.value==document.form.table52.value) { alert("Posição 09 não pode ser igual a Posição 52 "); return false; }
if(document.form.table09.value==document.form.table53.value) { alert("Posição 09 não pode ser igual a Posição 53 "); return false; }
if(document.form.table09.value==document.form.table54.value) { alert("Posição 09 não pode ser igual a Posição 54 "); return false; }
if(document.form.table09.value==document.form.table55.value) { alert("Posição 09 não pode ser igual a Posição 55 "); return false; }
if(document.form.table09.value==document.form.table56.value) { alert("Posição 09 não pode ser igual a Posição 56 "); return false; }
if(document.form.table09.value==document.form.table57.value) { alert("Posição 09 não pode ser igual a Posição 57 "); return false; }
if(document.form.table09.value==document.form.table58.value) { alert("Posição 09 não pode ser igual a Posição 58 "); return false; }
if(document.form.table09.value==document.form.table59.value) { alert("Posição 09 não pode ser igual a Posição 59 "); return false; }
if(document.form.table09.value==document.form.table60.value) { alert("Posição 09 não pode ser igual a Posição 60 "); return false; }
if(document.form.table09.value==document.form.table61.value) { alert("Posição 09 não pode ser igual a Posição 61 "); return false; }
if(document.form.table09.value==document.form.table62.value) { alert("Posição 09 não pode ser igual a Posição 62 "); return false; }
if(document.form.table09.value==document.form.table63.value) { alert("Posição 09 não pode ser igual a Posição 63 "); return false; }
if(document.form.table09.value==document.form.table64.value) { alert("Posição 09 não pode ser igual a Posição 64 "); return false; }
if(document.form.table09.value==document.form.table65.value) { alert("Posição 09 não pode ser igual a Posição 65 "); return false; }
if(document.form.table09.value==document.form.table66.value) { alert("Posição 09 não pode ser igual a Posição 66 "); return false; }
if(document.form.table09.value==document.form.table67.value) { alert("Posição 09 não pode ser igual a Posição 67 "); return false; }
if(document.form.table09.value==document.form.table68.value) { alert("Posição 09 não pode ser igual a Posição 68 "); return false; }
if(document.form.table09.value==document.form.table69.value) { alert("Posição 09 não pode ser igual a Posição 69 "); return false; }
if(document.form.table09.value==document.form.table70.value) { alert("Posição 09 não pode ser igual a Posição 70 "); return false; }
if(document.form.table10.value==document.form.table11.value) { alert("Posição 10 não pode ser igual a Posição 11 "); return false; }
if(document.form.table11.value==document.form.table12.value) { alert("Posição 11 não pode ser igual a Posição 12 "); return false; }
if(document.form.table12.value==document.form.table13.value) { alert("Posição 12 não pode ser igual a Posição 13 "); return false; }
if(document.form.table13.value==document.form.table14.value) { alert("Posição 13 não pode ser igual a Posição 14 "); return false; }
if(document.form.table14.value==document.form.table15.value) { alert("Posição 14 não pode ser igual a Posição 15 "); return false; }
if(document.form.table15.value==document.form.table16.value) { alert("Posição 15 não pode ser igual a Posição 16 "); return false; }
if(document.form.table16.value==document.form.table17.value) { alert("Posição 16 não pode ser igual a Posição 17 "); return false; }
if(document.form.table17.value==document.form.table18.value) { alert("Posição 17 não pode ser igual a Posição 18 "); return false; }
if(document.form.table18.value==document.form.table19.value) { alert("Posição 18 não pode ser igual a Posição 19 "); return false; }
if(document.form.table19.value==document.form.table20.value) { alert("Posição 19 não pode ser igual a Posição 20 "); return false; }
if(document.form.table20.value==document.form.table21.value) { alert("Posição 20 não pode ser igual a Posição 21 "); return false; }
if(document.form.table21.value==document.form.table22.value) { alert("Posição 21 não pode ser igual a Posição 22 "); return false; }
if(document.form.table22.value==document.form.table23.value) { alert("Posição 22 não pode ser igual a Posição 23 "); return false; }
if(document.form.table23.value==document.form.table24.value) { alert("Posição 23 não pode ser igual a Posição 24 "); return false; }
if(document.form.table24.value==document.form.table25.value) { alert("Posição 24 não pode ser igual a Posição 25 "); return false; }
if(document.form.table25.value==document.form.table26.value) { alert("Posição 25 não pode ser igual a Posição 26 "); return false; }
if(document.form.table26.value==document.form.table27.value) { alert("Posição 26 não pode ser igual a Posição 27 "); return false; }
if(document.form.table27.value==document.form.table28.value) { alert("Posição 27 não pode ser igual a Posição 28 "); return false; }
if(document.form.table28.value==document.form.table29.value) { alert("Posição 28 não pode ser igual a Posição 29 "); return false; }
if(document.form.table29.value==document.form.table30.value) { alert("Posição 29 não pode ser igual a Posição 30 "); return false; }
if(document.form.table30.value==document.form.table31.value) { alert("Posição 30 não pode ser igual a Posição 31 "); return false; }
if(document.form.table31.value==document.form.table32.value) { alert("Posição 31 não pode ser igual a Posição 32 "); return false; }
if(document.form.table32.value==document.form.table33.value) { alert("Posição 32 não pode ser igual a Posição 33 "); return false; }
if(document.form.table33.value==document.form.table34.value) { alert("Posição 33 não pode ser igual a Posição 34 "); return false; }
if(document.form.table34.value==document.form.table35.value) { alert("Posição 34 não pode ser igual a Posição 35 "); return false; }
if(document.form.table35.value==document.form.table36.value) { alert("Posição 35 não pode ser igual a Posição 36 "); return false; }
if(document.form.table36.value==document.form.table37.value) { alert("Posição 36 não pode ser igual a Posição 37 "); return false; }
if(document.form.table37.value==document.form.table38.value) { alert("Posição 37 não pode ser igual a Posição 38 "); return false; }
if(document.form.table38.value==document.form.table39.value) { alert("Posição 38 não pode ser igual a Posição 39 "); return false; }
if(document.form.table39.value==document.form.table40.value) { alert("Posição 39 não pode ser igual a Posição 40 "); return false; }
if(document.form.table40.value==document.form.table41.value) { alert("Posição 40 não pode ser igual a Posição 41 "); return false; }
if(document.form.table41.value==document.form.table42.value) { alert("Posição 41 não pode ser igual a Posição 42 "); return false; }
if(document.form.table42.value==document.form.table43.value) { alert("Posição 42 não pode ser igual a Posição 43 "); return false; }
if(document.form.table43.value==document.form.table44.value) { alert("Posição 43 não pode ser igual a Posição 44 "); return false; }
if(document.form.table44.value==document.form.table45.value) { alert("Posição 44 não pode ser igual a Posição 45 "); return false; }
if(document.form.table45.value==document.form.table46.value) { alert("Posição 45 não pode ser igual a Posição 46 "); return false; }
if(document.form.table46.value==document.form.table47.value) { alert("Posição 46 não pode ser igual a Posição 47 "); return false; }
if(document.form.table47.value==document.form.table48.value) { alert("Posição 47 não pode ser igual a Posição 48 "); return false; }
if(document.form.table48.value==document.form.table49.value) { alert("Posição 48 não pode ser igual a Posição 49 "); return false; }
if(document.form.table49.value==document.form.table50.value) { alert("Posição 49 não pode ser igual a Posição 50 "); return false; }
if(document.form.table50.value==document.form.table51.value) { alert("Posição 50 não pode ser igual a Posição 51 "); return false; }
if(document.form.table51.value==document.form.table52.value) { alert("Posição 51 não pode ser igual a Posição 52 "); return false; }
if(document.form.table52.value==document.form.table53.value) { alert("Posição 52 não pode ser igual a Posição 53 "); return false; }
if(document.form.table53.value==document.form.table54.value) { alert("Posição 53 não pode ser igual a Posição 54 "); return false; }
if(document.form.table54.value==document.form.table55.value) { alert("Posição 54 não pode ser igual a Posição 55 "); return false; }
if(document.form.table55.value==document.form.table56.value) { alert("Posição 55 não pode ser igual a Posição 56 "); return false; }
if(document.form.table56.value==document.form.table57.value) { alert("Posição 56 não pode ser igual a Posição 57 "); return false; }
if(document.form.table57.value==document.form.table58.value) { alert("Posição 57 não pode ser igual a Posição 58 "); return false; }
if(document.form.table58.value==document.form.table59.value) { alert("Posição 58 não pode ser igual a Posição 59 "); return false; }
if(document.form.table59.value==document.form.table60.value) { alert("Posição 59 não pode ser igual a Posição 60 "); return false; }
if(document.form.table60.value==document.form.table61.value) { alert("Posição 60 não pode ser igual a Posição 61 "); return false; }
if(document.form.table61.value==document.form.table62.value) { alert("Posição 61 não pode ser igual a Posição 62 "); return false; }
if(document.form.table62.value==document.form.table63.value) { alert("Posição 62 não pode ser igual a Posição 63 "); return false; }
if(document.form.table63.value==document.form.table64.value) { alert("Posição 63 não pode ser igual a Posição 64 "); return false; }
if(document.form.table64.value==document.form.table65.value) { alert("Posição 64 não pode ser igual a Posição 65 "); return false; }
if(document.form.table65.value==document.form.table66.value) { alert("Posição 65 não pode ser igual a Posição 66 "); return false; }
if(document.form.table66.value==document.form.table67.value) { alert("Posição 66 não pode ser igual a Posição 67 "); return false; }
if(document.form.table67.value==document.form.table68.value) { alert("Posição 67 não pode ser igual a Posição 68 "); return false; }
if(document.form.table68.value==document.form.table69.value) { alert("Posição 68 não pode ser igual a Posição 69 "); return false; }
if(document.form.table69.value==document.form.table70.value) { alert("Posição 69 não pode ser igual a Posição 70 "); return false; }
} 